---
title: "Can electricity consumption patterns tell us anything about the pandemic?"
author: "By Harri Somakanthan"
output:
  html_document: 
    toc: false
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(dplyr)
library(plotly)
library(itertools)
```







```{r fig.cap="Figure 1: Descriptive Plots" , echo=FALSE, fig.align='left', fig.height=9, fig.width=26, results='hide'}

# fr = read.csv("eurodata/fr.csv", header =TRUE, stringsAsFactors = FALSE)
# fr$end = fr$end %>% as.Date()
# fr = aggregate(fr["load"], by=fr["end"], sum)
# fr = fr[1:(length(fr$load)-1),]
# fr = fr[(fr$end> "2018-01-01	" & fr$end < "2020-07-30"),]
# df = fr
# setwd("eurodata/")
# temp = list.files(pattern="*.csv")
# for (i in 1:length(temp)){
#   fr = read.csv(temp[i], header = TRUE, stringsAsFactors = FALSE)
#   fr = na.omit(fr)
#   fr$end = fr$end %>% as.Date()
#   fr = aggregate(fr["load"], by=fr["end"], sum)
#   fr = fr[1:(length(fr$load)-1),]
#   fr = fr[(fr$end> "2018-01-01	" & fr$end < "2020-07-30"),]
#   fr[,paste0(temp[i])] = fr$load
#   df = left_join(df, fr, by=c("end"))
# }
# df = df[, -grep("load", colnames(df))]
# colnames(df) = c('end', 'Austria', 'Belgium', 'Switzerland', 'Germany', 'Denmark', 'Spain', 'France', 'UK', 'Ireland', 'Italy', 'Luxembourg', 'Netherlands', 'Norway', 'Portugal','Sweden')
# 
# dfwide = gather(df, country, load, Austria:Sweden, factor_key=TRUE)
# 
# write.csv(dfwide, 'widedata.csv')
# dfwide = read.csv("widedata.csv", header =TRUE, stringsAsFactors = FALSE)
# dfwide = dfwide[-1]
```

```{r fig.cap="Figure 1: Descriptive Plots" , echo=FALSE, fig.align='left', fig.height=4.5, fig.width=9, results='show'}

# p <- plot_ly() %>%
#   add_trace( data = dfwide, x = ~end, y = ~load, type = 'scatter', 
#              mode = 'lines', color = ~as.factor(country))
# p <- plotly_build(p)
# 
# legendItems <- list(Austria = 'legendonly', Belgium= 'legendonly', Switzerland= 'legendonly', Germany= 'legendonly', Denmark= 'legendonly', Spain= 'legendonly', France= TRUE, UK= 'legendonly', Ireland= 'legendonly', Italy= TRUE, Luxembourg= 'legendonly', Netherlands= 'legendonly', Norway= 'legendonly', Portugal= 'legendonly', Sweden= 'legendonly')
# 
# for(i in seq_along(p$x$data)){
#   p$x$data[[i]]$visible <- legendItems[[p$x$data[[i]]$name]]
# }
# 
# #### LONG FORMAT DATA 
# # fig = plot_ly(df, x = ~end, y = ~Spain, name = "Spain", type = 'scatter', mode = 'lines', colors = "red") 
# # xy.list <- as.list(as.data.frame((df)))
# # for(i in colnames(df)[-1]) { fig <- add_trace(fig, y=xy.list[[i]], x=xy.list[['end']], 
# #                                               name = paste0(i),  type = 'scatter', 
# #                                               mode = 'lines',evaluate = TRUE) }
# 
# p = p %>% layout(title = 'Energy Consumption in Western Europe',
#          xaxis = list(title = 'Time'),
#          yaxis = list(title = 'Energy Consumption (MW)'))
# 
# p = p %>%
#     layout(xaxis = list(
#         range = 
#             c(as.numeric(as.POSIXct("2018-00-01", format="%Y-%m-%d"))*1000,
#               as.numeric(as.POSIXct("2020-07-30", format="%Y-%m-%d"))*1000),
#         type = "date"))
# 
# p

```




```{r fig.cap="Figure 2: Descriptive Plots" , echo=FALSE, fig.align='left', fig.height=9, fig.width=26, results='hide'}
# fr = read.csv("eurodata/fr.csv", header =TRUE, stringsAsFactors = FALSE)
# fr = na.omit(fr)
# fr$end = fr$end %>% as.Date()
# fr = aggregate(fr["load"], by=fr["end"], sum)
# fr = fr[1:(length(fr$load)-1),]
# TRAIN2015TO2018 = fr[(fr$end> "2015-01-01	" & fr$end < "2018-12-31"),]
# TEST2017 = fr[(fr$end> "2017-01-01" & fr$end < "2017-07-30"),]
# TEST2018 = fr[(fr$end> "2018-01-01" & fr$end < "2018-07-30"),]
# TEST2019 = fr[(fr$end> "2019-01-01" & fr$end < "2019-07-30"),]
# TRAIN2016TO2019 = fr[(fr$end> "2016-01-01	" & fr$end < "2019-12-31"),]
# TEST2020 = fr[(fr$end> "2020-01-01" & fr$end < "2020-07-30"),]
# 
# x1 = ggplot(fr, aes(x=end, y=load, color = "Electricity Consumed")) +
#   geom_line(size = 2) + theme_minimal() +
#   xlab("Date") + ylab("MW of Electricity Consumed") + scale_x_date(date_labels = "%Y") + ggtitle("FRANCE ELECTRICITY CONSUMPTION")
# 
# fcBESTFIT1 = readRDS(file = "eurodata/bf1.rds")
# fcBESTFIT2 = readRDS(file = "eurodata/bf2.rds")
# p = readRDS(file = "eurodata/p.rds")
# q = readRDS(file = "eurodata/q.rds")
# 
# lay <- rbind(c(1,1,1,1),
#              c(2,2,3,3))
# 
# grid.arrange(x1, p, q, layout_matrix = lay)
#  

```


<!-- The top plot in figure 1. is a time-series of electricity consumption in France. The bottom two plots show a SARIMAX model predicting energy consumption in 2019 vs 2020, having been trained on the previous 4 years worth of data. Table 1 shows the accuracy of this model on various European countries. The methodology behind this is explained in Appendix 4.1.  -->

<!-- The objective of this plot and table is to illustrate the predictability of electricity consumption data during a normal year vs a pandemic enduced year. The change is clearly picked up in the drastic changes in accuracy shown in table 1. Electricity consumption can be attributed to weather, seasonality, business cycles & base load. Weather and seasonality are in present moment indicators. The temperature causes one to use heating and cooling measures. Seasonality will effect the duration of lighting usage. Business cycles and base load (level of business activity) can be presumptiously reactive to conditions unlike weather and seasonality which are reactive in the moment. Hence, electricity consumption attributed to business cycles and base load can be a forward looking indicator into economic activity. -->

<!-- When diving into the plots individually of each country, it is clear that electricity consumption is reactive to policy changes. Using France as an example, their full lockdown began 12 weeks into 2020 and ended in week 20. The bottom right plot in figure 1 shows the forecast is almost perfectly out of place between week 12 and 20, before lining up again with the actual consumption.  -->

<!-- \begin{table}[!htbp] \centering  -->
<!--   \caption{Accuracy of SARIMAX on various countries} -->
<!--   \label{tab:my-table} -->
<!-- \begin{tabular}{llllll} -->
<!-- \\[-1.8ex]\hline  -->
<!-- \hline \\[-1.8ex]  -->
<!--  & ME & RMSE & MAE & MPE & MAPE \\ -->
<!-- \hline \\[-1.8ex]  -->
<!-- FRANCE TEST 2019 & -2925.663 & 90265.63 & 70169.87 & -0.4553922 & 5.26192 \\ -->
<!-- FRANCE TEST 2020 & -107436.7 & 143925.8 & 114499.1 & -9.782641 & 10.21085 \\ -->
<!-- GERMANY TEST 2019 & 610927.5 & 672348.8 & 649246.9 & 11.0203 & 11.92293 \\ -->
<!-- GERMANY TEST 2020 & -264620.9 & 407832.7 & 318019.9 & -5.713203 & 6.627528 \\ -->
<!-- SPAIN TEST 2019 & 6880.948 & 49946.31 & 40349.3 & 0.4713497 & 5.799492 \\ -->
<!-- SPAIN TEST 2020 & -50412.72 & 68669.14 & 58031.49 & -8.72553 & 9.714945 \\ -->
<!-- UNITED KINGDOM 2019 & 7891.58 & 90497.34 & 62057.25 & 0.07401255 & 4.054127 \\ -->
<!-- UNITED KINGDOM 2020 & -128479.9 & 172001.5 & 138371.7 & -9.760755 & 10.28156 \\ -->
<!-- SWEDEN 2019 & -580.2107 & 26802.2 & 21601.13 & -0.7898409 & 5.681146 \\ -->
<!-- SWEDEN 2020 & -16267.63 & 27859.37 & 21362.1 & -4.376811 & 5.734472 \\ -->
<!-- ITALY 2019 &  90675.5 & 105149.6 & 95438.57 & 10.63521 & 11.47715 \\ -->
<!-- ITALY 2020 &  91497.45 & 136313.6 & 115616.3 & 11.01898 & 15.24938 \\ -->
<!-- \hline \\[-1.8ex]  -->
<!-- \end{tabular} -->
<!-- \end{table} -->



# Duck Curve


```{r fig.cap="Figure 2: Descriptive Plots" , echo=FALSE, cache=FALSE, fig.align='left', fig.height=4.5, fig.width=9, results='show'}

fr = read.csv("eurodata/fr.csv", header =TRUE, stringsAsFactors = FALSE)
fr = na.omit(fr)
fr$hour = substr(fr$end,11,nchar(fr$end)-12)
fr$year = substr(fr$end,1,nchar(fr$end)-21)
fr  = aggregate(load ~ hour + year, data = fr, mean)
df = fr
setwd("eurodata/")
temp = list.files(pattern="*.csv")
for (i in 1:length(temp)){
  fr = read.csv(temp[i], header =TRUE, stringsAsFactors = FALSE)
  fr = na.omit(fr)
  fr$hour = substr(fr$end,11,nchar(fr$end)-12)
  fr$year = substr(fr$end,1,nchar(fr$end)-21)
  fr  = aggregate(load ~ hour + year, data = fr, mean)
  fr[,paste0(temp[i])] = fr$load
  df = left_join(df, fr, by=c("hour","year"))
}
df = df[, -grep("load", colnames(df))]
colnames(df) = c('hour','year', 'Austria', 'Belgium', 'Switzerland', 'Germany', 'Denmark', 'Spain', 'France', 'UK', 'Ireland', 'Italy', 'Luxembourg', 'Netherlands', 'Norway', 'Portugal','Sweden')

eurohourwide = gather(df, country, load, Austria:Sweden, factor_key=TRUE)
eurohourwide = eurohourwide[-3] 

country = c('Austria', 'Belgium', 'Switzerland', 'Germany', 'Denmark', 'Spain', 'France', 'UK', 'Ireland', 'Italy', 'Luxembourg', 'Netherlands', 'Norway', 'Portugal','Sweden')


# build up interactive element, the filter to the two groups
button_list <- lapply(1:length(country), function(x){
  list(method = "restyle",
       args = list("transforms[0].value", country[x]),
       label = country[x])
})

# fr = read.csv("fr.csv", header =TRUE, stringsAsFactors = FALSE)
# fr = na.omit(fr)
# fr$hour = substr(fr$end,11,nchar(fr$end)-12)
# fr$year = substr(fr$end,1,nchar(fr$end)-21)
# fr  = aggregate(load ~ hour + year, data = fr, mean)


p <- plot_ly(data = eurohourwide, x = ~hour, y = ~load, type = 'scatter', text = ~year, hoverinfo =~as.factor(year),
             mode = 'markers',  marker = list(color = ~as.factor(year), size = 8, opacity = 0.8),
             # color = ~as.factor(year), alpha = 0.7, 
             transforms = list( list(
                            type = 'filter',
                            # groups = eurohourwide$country
                            target = ~country,
                            operation = '=',
                            value = unique(eurohourwide$country)[1]
      ))) %>% layout(
        title = paste0('Intraday Energy Consumption'),
         xaxis = list(title = 'Hour of Day'),
         yaxis = list(title = 'MW of Energy'),
    updatemenus = list(
      list(
  xanchor = 'left',
  yanchor = "top",
  pad = list('r'= 0, 't'= 10, 'b' = 10),
  x = 0,
  y = 1.27,
        type = 'dropdown',
        active = 0,
        buttons = button_list
          
          # list(
          # list(method = "restyle",
          #      args = list("transforms[0].value", unique(eurohourwide$country)[1]),
          #      label = unique(eurohourwide$country)[1]),
          # list(method = "restyle",
          #      args = list("transforms[0].value", unique(eurohourwide$country)[2]),
          #      label = unique(eurohourwide$country)[2]),
          # list(method = "restyle",
          #      args = list("transforms[0].value", unique(eurohourwide$country)[3]),
          #      label = unique(eurohourwide$country)[3])
        )
      )
    )
  
p <- plotly_build(p)

# p = p %>% layout(title = 'Intraday Energy Consumption',
#          xaxis = list(title = 'Time'),
#          yaxis = list(title = 'MW of Energy'))
p


# # build up interactive element, the filter to the two groups
# button_list <- lapply(1:length(country), function(x){
#   list(method = "restyle",
#        args = list("transforms[0].value", country[x]),
#        label = country[x])
# })
# 
# type_list <-  list(
#   type = 'dropdown',
#   active = 0,
#   xanchor = 'center',
#   yanchor = "top",
#   pad = list('r'= 0, 't'= 10, 'b' = 10),
#   x = 0.5,
#   y = 1.27,
#   buttons = button_list
# )
# 
# # make plot, color based on the individual in the group
# plot_ly(eurohourwide, x = ~hour, y = ~load, mode = "markers",
#         color = ~as.factor(year), 
#         # colors = brewer.pal(3, "Set1"),
#         hoverinfo = "text", text = ~paste(year),
#         transforms = list(
#           list(
#             type = 'filter',
#             target = ~country,
#             operation = '=',
#             value = eurohourwide$country[1]
#           ))
#         ) %>%
#           layout(updatemenus = list(
#                    type_list
#                  ))

```



<div style="text-align: center;"><iframe width="560" height="315" src="https://www.youtube.com/embed/YYLzss58CLs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>



```{r, echo=FALSE,}
# sample(2009:2011, 150, replace=TRUE)
# set.seed(42)
# iris$year <- sample(2009:2011, 150, replace=TRUE) #MAKING FAKE YEAR DATA
# 
# p <- iris %>%
#   plot_ly(
#     type = 'scatter', 
#     x = ~Sepal.Length, 
#     y = ~Petal.Length,
#     color = ~as.factor(year), # GROUPING BY YEAR
#     ####### SAMPLE SOLUTION ########
#     # marker = list(color = ~as.factor(year), size = 8, opacity = 0.8),
#     text = ~Species, # ADDED THIS TO ILLUSTRATE THAT THERE WRONG DATA IN THE TRANSFORMATION
#     mode = 'markers', # IN MY EXAMPLE IM USING LINES, IT DOESNT MAKE SENSE TO USE IT HERE SO IM LEAVING IT AS MARKERS
#     transforms = list(
#       list(
#         type = 'filter',
#         target = ~Species,
#         operation = '=',
#         value = unique(iris$Species)[1]
#       )
#   )) %>% layout(
#     updatemenus = list(
#       list(
#         type = 'dropdown',
#         active = 0,
#         buttons = list(
#           list(method = "restyle",
#                args = list("transforms[0].value", unique(iris$Species)[1]),
#                label = unique(iris$Species)[1]),
#           list(method = "restyle",
#                args = list("transforms[0].value", unique(iris$Species)[2]),
#                label = unique(iris$Species)[2]),
#           list(method = "restyle",
#                args = list("transforms[0].value", unique(iris$Species)[3]),
#                label = unique(iris$Species)[3])
#         )
#       )
#     )
#   )
# 
# p
```













```{r shinyapp, echo=FALSE}
# 
# library(shiny)
# # Rely on the 'WorldPhones' dataset in the datasets
# # package (which generally comes preloaded).
# library(datasets)
# 
# ui <- fluidPage(
#   headerPanel("Intraday Energy Consumption"),
#   sidebarPanel(
#     selectInput('country','Country', c('Austria', 'Belgium', 'Switzerland', 'Germany', 'Denmark', 'Spain', 'France', 'UK', 'Ireland', 'Italy', 'Luxembourg', 'Netherlands', 'Norway', 'Portugal','Sweden')),
#     selected = 'Sweden'),
#   mainPanel(
#     plotlyOutput('plot')
#   )
# )
# 
# server <- function(input, output) {
#   
#   
#   d <- reactive({
#     eurohourwide %>% filter(country == input$country)
#     
#     
#   })
#   
#   
#   output$plot <- renderPlotly(
#     plot1 <-  plot_ly() %>% add_trace( data = d(), x = ~hour, y = ~load, type = 'scatter',
#              mode = 'lines', color = ~as.factor(year), alpha = 0.7) %>% 
#       layout(title = paste0('Intraday Energy Consumption in ',input$country),
#          xaxis = list(title = 'Hour of Day'),
#          yaxis = list(title = 'MW of Energy'))
#     
#   )
# 
# }
# 
# 
# deps = lapply(extensions, extDependency) 
#  if (filter != 'none') deps = c(deps, filterDependencies()) 
#  htmlwidgets::createWidget( 
#    'datatables', params, package = 'shiny', width = '100%', height = 'auto', 
#    dependencies = deps 
#  ) 
# 
# 
# shinyApp(ui,server, options = list(height = 500))
```


















