---
output:
  html_document:
    toc: false
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
library(tidyverse)
library(dplyr)
library(plotly)
library(scales)
```


```{r fig.cap="Figure 1: Descriptive Plots" , echo=FALSE, fig.align='left', fig.height=9, fig.width=26, results='hide'}

# fr = read.csv("eurodata/fr.csv", header =TRUE, stringsAsFactors = FALSE)
# fr$end = fr$end %>% as.Date()
# fr = aggregate(fr["load"], by=fr["end"], sum)
# fr = fr[1:(length(fr$load)-1),]
# fr = fr[(fr$end> "2018-01-01	" & fr$end < "2020-07-30"),]
# df = fr
# setwd("eurodata/")
# temp = list.files(pattern="*.csv")
# for (i in 1:length(temp)){
#   fr = read.csv(temp[i], header = TRUE, stringsAsFactors = FALSE)
#   fr = na.omit(fr)
#   fr$end = fr$end %>% as.Date()
#   fr = aggregate(fr["load"], by=fr["end"], sum)
#   fr = fr[1:(length(fr$load)-1),]
#   fr = fr[(fr$end> "2018-01-01	" & fr$end < "2020-07-30"),]
#   fr[,paste0(temp[i])] = fr$load
#   df = left_join(df, fr, by=c("end"))
# }
# df = df[, -grep("load", colnames(df))]
# colnames(df) = c('end', 'Austria', 'Belgium', 'Switzerland', 'Germany', 'Denmark', 'Spain', 'France', 'UK', 'Ireland', 'Italy', 'Luxembourg', 'Netherlands', 'Norway', 'Portugal','Sweden')
# 
# dfwide = gather(df, country, load, Austria:Sweden, factor_key=TRUE)
# 
# write.csv(dfwide, 'widedata.csv')
```

### Comparing Electricity Consumption to Weather in Australia


```{r fig.cap="Figure 2: Australian Plots" , echo=FALSE, fig.align='left', fig.height=4.5, fig.width=9, results='show'}

aus = read.csv("ausdata/VIC/PRICE_AND_DEMAND_201801_VIC1.csv", header =TRUE, stringsAsFactors = FALSE)
aus$SETTLEMENTDATE = aus$SETTLEMENTDATE %>% as.Date()
aus = aggregate(aus["TOTALDEMAND"], by=aus["SETTLEMENTDATE"], sum)
aus = aus %>% filter(TOTALDEMAND > 10000)
# setwd("ausdata/VIC/")
temp = list.files("ausdata/VIC/",pattern="*.csv")
for (i in 1:length(temp)){
  ausx = read.csv(paste0("ausdata/VIC/",temp[i]), header = TRUE, stringsAsFactors = FALSE)
  ausx$SETTLEMENTDATE = ausx$SETTLEMENTDATE %>% as.Date()
  ausx = aggregate(ausx["TOTALDEMAND"], by=ausx["SETTLEMENTDATE"], sum)
  ausx = ausx %>% filter(TOTALDEMAND >= 10000)
  # namex =  gsub('PRICE_AND_DEMAND_', '', temp[i])
  # namex =  gsub('_VIC1.csv', '', namex)
  aus = rbind(aus, ausx)
}

finalaus = aus
aus = read.csv("ausdata/NSW/PRICE_AND_DEMAND_201801_NSW1.csv", header =TRUE, stringsAsFactors = FALSE)
aus$SETTLEMENTDATE = aus$SETTLEMENTDATE %>% as.Date()
aus = aggregate(aus["TOTALDEMAND"], by=aus["SETTLEMENTDATE"], sum)
aus = aus %>% filter(TOTALDEMAND > 10000)

temp = list.files("ausdata/NSW/",pattern="*.csv")
for (i in 1:length(temp)){
  ausx = read.csv(paste0("ausdata/NSW/",temp[i]), header = TRUE, stringsAsFactors = FALSE)
  ausx$SETTLEMENTDATE = ausx$SETTLEMENTDATE %>% as.Date()
  ausx = aggregate(ausx["TOTALDEMAND"], by=ausx["SETTLEMENTDATE"], sum)
  ausx = ausx %>% filter(TOTALDEMAND >= 10000)
  # namex =  gsub('PRICE_AND_DEMAND_', '', temp[i])
  # namex =  gsub('_VIC1.csv', '', namex)
  aus = rbind(aus, ausx)
}

aus$NSW = aus$TOTALDEMAND
aus$VIC = finalaus$TOTALDEMAND
aus = aus[, -grep("TOTALDEMAND", colnames(aus))]

auswide = gather(aus, state, load, NSW:VIC, factor_key=TRUE)


weather = read.csv(paste0("ausdata/vicweather.csv"), header = TRUE, stringsAsFactors = FALSE)
weather = gather(weather, Month, temp, Jan:Dec, factor_key=TRUE)
weather$Date = as.Date(with(weather, paste(Year, Month,'1',sep="-")), "%Y-%b-%d")
weather = weather[(weather$Date >= "2018-01-01	" & weather$Date <= "2020-08-30"),]
weather$temp = rescale(weather$temp, to=c(min(auswide[auswide$state == 'VIC',]$load)*1.15,max(auswide[auswide$state == 'VIC',]$load)*0.85))
weather = weather[order(as.Date(weather$Date, format="%Y/%m/%d")),]


rainfall = read.csv(paste0("ausdata/vicrainfall.csv"), header = TRUE, stringsAsFactors = FALSE)
rainfall = gather(rainfall, Month, rain, Jan:Dec, factor_key=TRUE)
rainfall$Date = as.Date(with(rainfall, paste(Year, Month,'1',sep="-")), "%Y-%b-%d")
rainfall = rainfall[(rainfall$Date >= "2018-01-01	" & rainfall$Date <= "2020-08-30"),]
rainfall$rain = rescale(rainfall$rain, c(min(auswide[auswide$state == 'VIC',]$load)*1.15,max(auswide[auswide$state == 'VIC',]$load)*0.85))
rainfall = rainfall[order(as.Date(rainfall$Date, format="%Y/%m/%d")),]


p <- plot_ly() %>%
  add_trace( data = auswide, x = ~SETTLEMENTDATE, y = ~load, type = 'scatter',
             mode = 'lines', color = ~as.factor(state), colors =c("#e63946", "#415a77"),alpha = 0.7)


p = p %>% add_trace(data = weather, x = ~Date, y = ~temp, type = 'scatter',line=list(color='#48cae4',dash='dashed'),
             mode = 'lines', name = 'VIC SCALED TEMP', alpha = 0.9)

p = p %>% add_trace(data = rainfall, x = ~Date, y = ~rain, type = 'scatter',line=list(color='#0077b6',dash='dashed'),
             mode = 'lines', name = 'VIC SCALED RAIN', alpha = 1)

p <- plotly_build(p)

p = p %>% layout(title = 'Energy Consumption in Australia',
         xaxis = list(title = 'Time'),
         yaxis = list(title = 'Energy Consumption (MW)'))

p = p %>%
    layout(xaxis = list(
        range = 
            c(as.numeric(as.POSIXct("2018-01-01", format="%Y-%m-%d"))*1000,
              as.numeric(as.POSIXct("2020-08-30", format="%Y-%m-%d"))*1000),
        type = "date"))


legendItems <- list(NSW = 'legendonly', VIC = T, `VIC SCALED TEMP` = T, `VIC SCALED RAIN` = 'legendonly')

for(i in seq_along(p$x$data)){
  p$x$data[[i]]$visible <- legendItems[[p$x$data[[i]]$name]]
}

p

```


```{r fig.cap="Figure 1: European Plots" , echo=FALSE, fig.align='left', fig.height=4.5, fig.width=9, results='show'}
dfwide = read.csv("widedata.csv", header =TRUE, stringsAsFactors = FALSE)
dfwide = dfwide[-1]
p <- plot_ly() %>%
  add_trace( data = dfwide, x = ~end, y = ~load, type = 'scatter',
             mode = 'lines', color = ~as.factor(country))
p <- plotly_build(p)

legendItems <- list(Austria = 'legendonly', Belgium= 'legendonly', Switzerland= 'legendonly', Germany= 'legendonly', Denmark= 'legendonly', Spain= 'legendonly', France= TRUE, UK= 'legendonly', Ireland= 'legendonly', Italy= TRUE, Luxembourg= 'legendonly', Netherlands= 'legendonly', Norway= 'legendonly', Portugal= 'legendonly', Sweden= 'legendonly')

for(i in seq_along(p$x$data)){
  p$x$data[[i]]$visible <- legendItems[[p$x$data[[i]]$name]]
}

#### LONG FORMAT DATA
# fig = plot_ly(df, x = ~end, y = ~Spain, name = "Spain", type = 'scatter', mode = 'lines', colors = "red")
# xy.list <- as.list(as.data.frame((df)))
# for(i in colnames(df)[-1]) { fig <- add_trace(fig, y=xy.list[[i]], x=xy.list[['end']],
#                                               name = paste0(i),  type = 'scatter',
#                                               mode = 'lines',evaluate = TRUE) }

p = p %>% layout(title = 'Energy Consumption in Western Europe',
         xaxis = list(title = 'Time'),
         yaxis = list(title = 'Energy Consumption (MW)'))

p = p %>%
    layout(xaxis = list(
        range =
            c(as.numeric(as.POSIXct("2018-00-01", format="%Y-%m-%d"))*1000,
              as.numeric(as.POSIXct("2020-07-30", format="%Y-%m-%d"))*1000),
        type = "date"))

p
```




# Things to do tomorrow night: 

- make the SARIMAX for Australian data. 
- show the latex table on the analysis between VICTORIA and NEW SOUTH WALES 


look into:
  - mutiple change points
  - chain point analysis
  - intervention analysis 

